# Application identity
spring.application.name=policy-service
server.port=8082

# MySQL datasource configuration (CI/CD DB)
spring.datasource.url=jdbc:mysql://ci-db-server:3306/policydb_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=ci_user
spring.datasource.password=ci_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true